### DISCUSSION TITLE
Differentiate between role name and role key

### DISCUSSION THREAD

**Discussion by RafaelKr** [sulu/SuluCommunityBundle#177] [General]
We're creating a role called `Portal Customer`. We'd like to use the role key `portal_customer` for that. Especially because for Symfony the role would be called `ROLE_SULU_PORTAL CUSTOMER` (note the space) without setting the key.

I'd like to create a PR, but we have the following options:

1. Create a new configuration key in `config/packages/sulu_community.yaml` with the path `sulu_community.website.role_name` corresponding to the `role` configuration option.
 
2. Create the PR to https://github.com/sulu/sulu and adjust the following line to replace spaces with underscores: https://github.com/sulu/sulu/blob/15a676466de29d815d016b37dd7cb97fef1cc76d/src/Sulu/Bundle/SecurityBundle/Entity/Role.php#L130. Of course this would be a breaking change so the PR would be against the 3.0 branch.
Also the [AsciiSlugger](https://symfony.com/doc/current/string.html#slugger) could be used which is available from Symfony 5.0, using `_` as the seperator.

3. Doing both PRs

What is your preferred approach to that? Of course I'm open to other solutions too.

Edit: `AsciiSlugger` is available starting from Symfony 5.0, before I told it's available from 7.1 as that is what the version selector in the documentation suggested.

**Comment by alexander-schranz** [comment]
@RafaelKr you can create "static roles" which you use in code via fixtures and call in the fixtures `$role->setKey('PORTAL_CUSTOMER');` to force the key you like to access in your firewall settings and somewhere else.

**Reply by RafaelKr** [reply]
We already implemented a custom Builder (which is added as dependency for the `Sulu\Bundle\CommunityBundle\Build\CommunityBuilder` command via service decoration). The builder is adding the role `Portal Customer` with the key `portal_customer`. But we also want to use that role for the Community bundle. 

When using config 1:
```yaml
sulu_community:
  webspaces:
    website:
      role: 'Portal Customer'

[...]
```
when running `bin/adminconsole sulu:build maintain` it results in
![image](https://github.com/user-attachments/assets/1b66f5c0-4b70-4441-9341-3752435894ec)


When using config 2:
```yaml
sulu_community:
  webspaces:
    website:
      role: 'portal_customer'

[...]
```
it's failing on user registration.


For now we're using the following workaround.
```yaml
parameters:
  env(ROLE_PORTAL_CUSTOMER): 'Portal Customer'

sulu_community:
  webspaces:
    website:
      # TODO: https://github.com/sulu/SuluCommunityBundle/discussions/177
      # role_key: 'portal_customer'
      # use an env var until the linked discussion 177 is resolved
      # We need to run `ROLE_PORTAL_CUSTOMER=portal_customer bin/adminconsole sulu:build maintain --no-interaction`
      role: '%env(ROLE_PORTAL_CUSTOMER)%'

[...]
```

It would be much easier to be able to do
```yaml
sulu_community:
  webspaces:
    website:
      role_key: 'portal_customer'
      role: 'Portal Customer'

[...]
```
