### ISSUE TITLE
Adjust documentation to explicitly set provider in test environment 

### ISSUE THREAD

**Issue by nnatter** [sulu/SuluCommunityBundle#111]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Community Bundle Version | 26634972fc596da361446c87603de3c366018748

#### Expected Behavior

The configuration for the security bundle in the test environment (https://github.com/sulu/SuluCommunityBundle/blob/develop/Resources/doc/2-setup-webspace.md#enable-security) in the documentation should set the `provider` to `testprovider`. Otherwise, the `security:check` command will throw the following error:

 ```
Not configuring explicitly the provider for the "form_login" listener on "webspace-xyz" firewall is ambiguous as there is more than one registered provider.
```

Furthermore, the configuration should also activate the TestUserProvider of Sulu with the following config:
```
security:
    # ...
    firewalls:
        <webspace_key>:
            provider: testprovider
            # ...

sulu_test:
    enable_test_user_provider: true
```

Otherwise the configuration will lead to the following error:
```
The service "security.context_listener.0" has a dependency on a non-existent service "test_user_provider".
```
