### ISSUE TITLE
Bundle not working on Postgres

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluCommunityBundle#173]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Community Bundle Version | 2.0@dev: 17e2867a4caae61a295d32811838de24a112c5a4
| Sulu Version | -
| Browser Version | -

#### Actual Behavior

The current bundle version is not working on postgres as the SQL errors with:

![grafik](https://github.com/user-attachments/assets/1685570b-0157-49c8-9dec-e05651bced1b)

#### Expected Behavior

It should not error.

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

```php
<?php

namespace App\Doctrine\Extension\Postgresql;

use Doctrine\ORM\Query\AST\Functions\FunctionNode;
use Doctrine\ORM\Query\Parser;
use Doctrine\ORM\Query\SqlWalker;
use Doctrine\ORM\Query\TokenType;

class SimilarTo extends FunctionNode
{
    public $value = null;

    public $regexp = null;

    public function parse(Parser $parser): void
    {
        $parser->match(TokenType::T_IDENTIFIER);
        $parser->match(TokenType::T_OPEN_PARENTHESIS);
        $this->value = $parser->StringPrimary();
        $parser->match(TokenType::T_COMMA);
        $this->regexp = $parser->StringExpression();
        $parser->match(TokenType::T_CLOSE_PARENTHESIS);
    }

    public function getSql(SqlWalker $sqlWalker): string
    {
        return '(' . $this->value->dispatch($sqlWalker) . ' SIMILAR TO ' . $this->regexp->dispatch($sqlWalker) . ')';
    }
}
```

```yaml
doctrine:
    orm:
        dql:
            string_functions: App\Doctrine\Extension\Postgresql\SimilarTo 
```

**Comment by loalf** [comment]
I can confirm this solution actually works on `Postgres` but the configuration needs to be amended slightly for Symfony 7.

```
doctrine:
    orm:
        dql:
            string_functions: 
                REGEXP: App\Doctrine\Extension\Postgresql\SimilarTo 
```
