### ISSUE TITLE
Impossible to use email and name for from email configuration

### ISSUE THREAD

**Issue by Dodger77** [sulu/SuluCommunityBundle#175]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Community Bundle Version | 17e2867
| Sulu Version | 2.6.5
| Browser Version | n/a

#### Actual Behavior

Sending the password forgotten form leads to the following exception:

```Email "From name" does not comply with addr-spec of RFC 2822.```

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

Using [password forget feature](https://github.com/sulu/SuluCommunityBundle/blob/2.0/Resources/doc/7-password-forget.md) with following sulu_community.yaml

```
sulu_community:
    webspaces:
        my-webspace:
            from:
                email: 'text@example.com'
                name: 'From name'
```

The structure of CommunityManagerCompilerPass and MailFactory differ, e.g. for from email:

https://github.com/sulu/SuluCommunityBundle/blob/17e2867a4caae61a295d32811838de24a112c5a4/DependencyInjection/CompilerPass/CommunityManagerCompilerPass.php#L126

The config structure results to following array:

```
['text@example.com' => 'From name']
```

but https://github.com/sulu/SuluCommunityBundle/blob/17e2867a4caae61a295d32811838de24a112c5a4/Mail/MailFactory.php#L121 results to the value 'From name', not the key 'text@example.com'.

#### Possible Solutions

Fixing MailFactory::getAddress() in order to work with current configuration structure.
