### ISSUE TITLE
Make it possible to have separate email templates for html and plain-text

### ISSUE THREAD

**Issue by RafaelKr** [sulu/SuluCommunityBundle#178]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Community Bundle Version | ^2.0@dev, 17e2867a4caae61a295d32811838de24a112c5a4
| Sulu Version | 2.6.5
| Browser Version | -

#### Actual Behavior

Currently we can only define one email template per type ([registration](https://github.com/sulu/SuluCommunityBundle/blob/2.0/Resources/doc/5-registration.md), [email confirmation](https://github.com/sulu/SuluCommunityBundle/blob/2.0/Resources/doc/10-email-confirmation.md#config), ...).

If you use an HTML template Symfony will automatically generate a text version based on the following rules:
https://symfony.com/doc/current/mailer.html#text-content

When you have an advanced template with a footer with a lot of information this has the downside, that probably the indentation is completely off. Also sometimes we just want to have a different templates for html and text.

#### Expected Behavior

It would be good to be able to define two separate templates.

#### Steps to Reproduce

-

#### Possible Solutions

Maybe we could have `user_template` and `admin_template` and additionally `user_template_plain` and `admin_template_plain`.

Or, my preferred option, we define it like `user_template: community/email-confirmation-email` and it will automatically try to find `community/email-confirmation-email.html.twig` and `community/email-confirmation-email.txt.twig`.
Also see: https://symfony.com/doc/current/mailer.html#text-content

I'm open to create a PR for my preferred approach.

Btw instead of `new Email` we could also use `new TemplatedEmail`.

**Comment by RafaelKr** [comment]
The implementation we use in our project now:

`config/packages/sulu_community.yaml`
```yaml
sulu_community:
  webspaces:
    website:
      # ...

      registration:
        # ...
        email:
          subject: Registration
          # note there's no extension, it will load:
          # portal/email/auth/registration-email.html.twig as htmlTemplate
          # portal/email/auth/registration-email.txt.twig as textTemplate
          user_template: portal/email/auth/registration-email
          admin_template: ~
```

`config/services.yaml`
```yaml
services:
  # ...

  App\DependencyInjection\SuluCommunityBundle\Mail\MailFactory:
    decorates: sulu_community.mail_factory
    parent: sulu_community.mail_factory
```

`/src/DependencyInjection/SuluCommunityBundle/Mail/MailFactory.php`
```php
<?php

declare(strict_types=1);

namespace App\DependencyInjection\SuluCommunityBundle\Mail;

use Sulu\Bundle\CommunityBundle\Mail\MailFactory as BaseMailFactory;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;

/*
 * Decorates sulu_community.mail_factory
 *
 * This allows us to have separate templates for plain text and html
 * See: https://github.com/sulu/SuluCommunityBundle/discussions/177
 */
class MailFactory extends BaseMailFactory
{
    protected function sendEmail($from, $to, string $subject, string $template, array $data): void
    {
        if (!$this->getAddress($from) || !$this->getAddress($to)) {
            return;
        }

        $email = (new TemplatedEmail())
            ->context($data)
            ->subject($this->translator->trans($subject))
            ->from($this->getAddress($from))
            ->to($this->getAddress($to))
            ->htmlTemplate($this->templatePath($template, 'html'))
            ->textTemplate($this->templatePath($template, 'txt'));

        $this->mailer->send($email);
    }

    protected function templatePath(string $templateBasePath, string $extension): string
    {
        return \sprintf(
            '%s.%s.twig',
            $templateBasePath,
            $extension,
        );
    }
}
```
