### ISSUE TITLE
Document deactivate of client and proxy cache when use login-embed

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluCommunityBundle#40]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |
#### Actual Behavior

The cache is set normally to 240 which will make problems when the user logout and land again on the same page which he visited the last 240seconds.
#### Expected Behavior

It should be documented how to deactivate the client and proxy cache.:

```yml
sulu_http_cache:
    handlers:
        public:
            max_age: 0
            shared_max_age: 0
```
