### ISSUE TITLE
Implement from and to name for emails

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluCommunityBundle#52]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

#### Actual Behavior

Currently you can only set the from and to email address.

#### Expected Behavior

It should also be possible to set the from and to name. They should fallback to the webspace name when not set!

#### Possible Solutions

It should be allow the old syntax and the new one:

```yml
from: test@example.com
to: test@example.com
```

New:

```yml
from: 
    email: test@example.com
    name: Test
to: 
    email: test@example.com
    name: Test
```
